In [1]:
import torch

In [23]:
# 创建一个标签 tensor
labels = torch.tensor([1,2,3,1,2])

In [24]:
# 输出标签的形状
labels.shape

torch.Size([5])

In [25]:
# 创建一个大小 batch_size x batch_size 的对角矩阵矩阵
indices_equal = torch.eye(labels.size()[0]).type(torch.ByteTensor)

In [26]:
indices_equal

tensor([[1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1]], dtype=torch.uint8)

In [27]:
# 将上面对角矩阵进行反转
indices_not_equal = -(indices_equal - 1)

In [28]:
# 观察反转后的效果
indices_not_equal

tensor([[0, 1, 1, 1, 1],
        [1, 0, 1, 1, 1],
        [1, 1, 0, 1, 1],
        [1, 1, 1, 0, 1],
        [1, 1, 1, 1, 0]], dtype=torch.uint8)

In [29]:
# 1 x 5 x 5
# 这里用 2 表示在第 2 个维度，对每个元素包裹一层
i_not_equal_j = torch.unsqueeze(indices_not_equal, 2)

In [30]:
i_not_equal_j

tensor([[[0],
         [1],
         [1],
         [1],
         [1]],

        [[1],
         [0],
         [1],
         [1],
         [1]],

        [[1],
         [1],
         [0],
         [1],
         [1]],

        [[1],
         [1],
         [1],
         [0],
         [1]],

        [[1],
         [1],
         [1],
         [1],
         [0]]], dtype=torch.uint8)

In [31]:
# 1 x 5 x 5
# 这里用 2 表示在第 2 个维度，对每个元素包裹一层
i_not_equal_k = torch.unsqueeze(indices_not_equal, 1)

In [32]:
i_not_equal_k

tensor([[[0, 1, 1, 1, 1]],

        [[1, 0, 1, 1, 1]],

        [[1, 1, 0, 1, 1]],

        [[1, 1, 1, 0, 1]],

        [[1, 1, 1, 1, 0]]], dtype=torch.uint8)

In [33]:
j_not_equal_k = torch.unsqueeze(indices_not_equal, 0)

In [34]:
j_not_equal_k

tensor([[[0, 1, 1, 1, 1],
         [1, 0, 1, 1, 1],
         [1, 1, 0, 1, 1],
         [1, 1, 1, 0, 1],
         [1, 1, 1, 1, 0]]], dtype=torch.uint8)

In [35]:
distinct_indices = (i_not_equal_j & i_not_equal_k) & j_not_equal_k

In [36]:
distinct_indices

tensor([[[0, 0, 0, 0, 0],
         [0, 0, 1, 1, 1],
         [0, 1, 0, 1, 1],
         [0, 1, 1, 0, 1],
         [0, 1, 1, 1, 0]],

        [[0, 0, 1, 1, 1],
         [0, 0, 0, 0, 0],
         [1, 0, 0, 1, 1],
         [1, 0, 1, 0, 1],
         [1, 0, 1, 1, 0]],

        [[0, 1, 0, 1, 1],
         [1, 0, 0, 1, 1],
         [0, 0, 0, 0, 0],
         [1, 1, 0, 0, 1],
         [1, 1, 0, 1, 0]],

        [[0, 1, 1, 0, 1],
         [1, 0, 1, 0, 1],
         [1, 1, 0, 0, 1],
         [0, 0, 0, 0, 0],
         [1, 1, 1, 0, 0]],

        [[0, 1, 1, 1, 0],
         [1, 0, 1, 1, 0],
         [1, 1, 0, 1, 0],
         [1, 1, 1, 0, 0],
         [0, 0, 0, 0, 0]]], dtype=torch.uint8)

In [37]:
label_equal = (torch.unsqueeze(labels, 0) == torch.unsqueeze(labels, 1))

In [38]:
label_equal

tensor([[ True, False, False,  True, False],
        [False,  True, False, False,  True],
        [False, False,  True, False, False],
        [ True, False, False,  True, False],
        [False,  True, False, False,  True]])

In [39]:
i_equal_j = torch.unsqueeze(label_equal, 2)
i_equal_k = torch.unsqueeze(label_equal, 1)

In [40]:
valid_labels = (i_equal_j & ~i_equal_k)

In [41]:
mask = (distinct_indices.to('cpu').bool() & valid_labels)

In [42]:
mask

tensor([[[False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False,  True,  True, False,  True],
         [False, False, False, False, False]],

        [[False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [ True, False,  True,  True, False]],

        [[False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False]],

        [[False,  True,  True, False,  True],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False]],

        [[False, False, False, False, False],
         [ True, False,  T